/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module enemy_3 (
    input clk,
    input rst,
    input [10:0] cursorX,
    input [10:0] cursorY,
    output reg [10:0] enemyPosX,
    output reg [10:0] enemyPosY,
    output reg r,
    output reg g,
    output reg b
  );
  
  
  
  reg [10:0] M_charX_d, M_charX_q = 9'h190;
  reg [10:0] M_charY_d, M_charY_q = 7'h6e;
  reg [15:0] M_timer_d, M_timer_q = 1'h0;
  
  always @* begin
    M_charY_d = M_charY_q;
    M_charX_d = M_charX_q;
    M_timer_d = M_timer_q;
    
    r = 1'h0;
    g = 1'h0;
    b = 1'h0;
    if ((cursorX - M_charX_q + 5'h1a) > 1'h0 && (cursorX - M_charX_q + 5'h1a) < 7'h50) begin
      if ((cursorY - M_charY_q + 5'h1a) > 1'h0 && (cursorY - M_charY_q + 5'h1a) < 7'h64) begin
        r = 1'h1;
        g = 1'h0;
        b = 1'h0;
      end
    end else begin
      r = 1'h0;
      g = 1'h0;
      b = 1'h0;
    end
    if (M_timer_q == 1'h1) begin
      M_charX_d = M_charX_q + 1'h1;
      M_charY_d = M_charY_q + 1'h1;
    end
    if (M_timer_q == 2'h2) begin
      M_charX_d = M_charX_q + 1'h0;
      M_charY_d = M_charY_q + 1'h1;
    end
    M_timer_d = M_timer_q + 1'h1;
    enemyPosX = M_charX_q;
    enemyPosY = M_charY_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_charX_q <= 9'h190;
      M_charY_q <= 7'h6e;
      M_timer_q <= 1'h0;
    end else begin
      M_charX_q <= M_charX_d;
      M_charY_q <= M_charY_d;
      M_timer_q <= M_timer_d;
    end
  end
  
endmodule
