/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module projectile_5 (
    input clk,
    input rst,
    input [10:0] cursorX,
    input [10:0] cursorY,
    input [10:0] startX,
    input [10:0] startY,
    input hit,
    input shot,
    output reg [10:0] enemyPosX,
    output reg [10:0] enemyPosY,
    output reg r,
    output reg g,
    output reg b
  );
  
  
  
  reg [10:0] M_charX_d, M_charX_q = 1'h0;
  reg [10:0] M_charY_d, M_charY_q = 1'h0;
  reg M_start_d, M_start_q = 1'h0;
  localparam EXIST_state = 1'd0;
  localparam NOTEXIST_state = 1'd1;
  
  reg M_state_d, M_state_q = NOTEXIST_state;
  reg [17:0] M_timer_d, M_timer_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    M_charX_d = M_charX_q;
    M_start_d = M_start_q;
    M_charY_d = M_charY_q;
    M_timer_d = M_timer_q;
    
    r = 1'h0;
    g = 1'h0;
    b = 1'h0;
    if (M_start_q == 1'h0) begin
      M_charX_d = startX;
      M_charY_d = startY;
      M_start_d = M_start_q + 1'h1;
    end else begin
      if ((M_state_q == NOTEXIST_state) && (shot == 1'h1)) begin
        M_state_d = EXIST_state;
      end
      if (M_state_q == EXIST_state) begin
        if ((cursorX - M_charX_q + 5'h1a) > 1'h0 && (cursorX - M_charX_q + 5'h1a) < 4'hf) begin
          if ((cursorY - M_charY_q + 5'h1a) > 1'h0 && (cursorY - M_charY_q + 5'h1a) < 5'h1e) begin
            r = 1'h0;
            g = 1'h0;
            b = 1'h1;
          end
        end else begin
          r = 1'h0;
          g = 1'h0;
          b = 1'h0;
        end
      end else begin
        r = 1'h0;
        g = 1'h0;
        b = 1'h0;
      end
      M_timer_d = M_timer_q + 1'h1;
      if (M_timer_q == 1'h1) begin
        if ((M_state_q == EXIST_state) && (M_charY_q < 4'hf)) begin
          M_state_d = NOTEXIST_state;
          M_charX_d = startX;
          M_charY_d = startY;
        end
        if ((M_state_q == EXIST_state) && (hit == 1'h1)) begin
          M_state_d = NOTEXIST_state;
          M_charX_d = startX;
          M_charY_d = startY;
        end
        if (M_state_q == EXIST_state) begin
          M_charY_d = M_charY_q - 2'h2;
        end
      end
    end
    enemyPosX = M_charX_q;
    enemyPosY = M_charY_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_charX_q <= 1'h0;
      M_charY_q <= 1'h0;
      M_start_q <= 1'h0;
      M_timer_q <= 1'h0;
    end else begin
      M_charX_q <= M_charX_d;
      M_charY_q <= M_charY_d;
      M_start_q <= M_start_d;
      M_timer_q <= M_timer_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h1;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
