/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module aluADD_6 (
    input [31:0] a,
    input [31:0] b,
    input [5:0] alufn,
    output reg [31:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [32:0] temp;
  
  reg [32:0] over;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        temp = a + b;
        over = a - b;
      end
      2'h1: begin
        temp = a - b;
        over = a - b;
      end
      2'h2: begin
        temp = a * b;
        over = a - b;
      end
      2'h3: begin
        temp = a - (a / b * b);
        over = a - b;
      end
      default: begin
        temp = a + b;
        over = a - b;
      end
    endcase
    out = temp[0+31-:32];
    v = (a[31+0-:1] & ~b[31+0-:1] & (~over[31+0-:1])) | ((~a[31+0-:1]) & (b[31+0-:1]) & over[31+0-:1]);
    n = over[31+0-:1];
    z = (~|over);
  end
endmodule
