/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module user_3 (
    input [10:0] charX,
    input [10:0] charY,
    input [10:0] cursorX,
    input [10:0] cursorY,
    output reg r,
    output reg g,
    output reg b
  );
  
  
  
  always @* begin
    r = 1'h0;
    g = 1'h0;
    b = 1'h0;
    if ((cursorX - charX + 5'h1a) > 1'h0 && (cursorX - charX + 5'h1a) < 6'h28) begin
      if ((cursorY - charY + 5'h1a) > 1'h0 && (cursorY - charY + 5'h1a) < 6'h32) begin
        r = 1'h0;
        g = 1'h1;
        b = 1'h0;
      end
    end else begin
      r = 1'h0;
      g = 1'h0;
      b = 1'h0;
    end
  end
endmodule
